spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deng?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: deng1727
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.du.lin.bean
    

lin:
  kaptchaswich: true


    
  

      